### PR TITLE
Make statuses public on SearchResult

### LINKED ISSUE #140: Instance of SearchResult
Hi, I'm writing some unit tests on my app and I want to say my mock/fake returns a `SearchResult` with a `Status` inside it however everything I try fails to convert it from an array or List or ReadOnlyCollection to a `SearchResult`.

How can I construct a `SearchResult` with a `Status` in it?

### PR DESCRIPTION
**Pull request by jchannon**
Fixes #140

### CODE REVIEW

**Comment by azyobuzin** [comment]
You just made `statuses` property public. `statuses` is not suitable as a public property. So would you rename the property for example `Statuses`?

**Comment by chitoku-k** [comment]
I personally disagree with this PR. It is a lack of consistency to make `statuses` simply public, while other classes DO keep these inner lists private. You may write your own implementation to create mock objects from JSON because CoreTweet is basically designed to build an object from JSON response.

**Comment by jchannon** [comment]
I can understand that however I would ask why is everything in the code
base private?  Relying on a specific deserializer to set private properties
seems wrong. Making them all public wouldn't lose you anything as the
deserializer would still work but consumers of the library can work with
the classes easier

**Comment by chitoku-k** [comment]
They are all private because `SearchResult` provides enumerator, not a data store of `Status` as seen in its inheritances. As stated above it loses consistency with these interfaces, design and concept of the classes. It could be better if we provide mock generators for example without allowing users to overuse them in production code.

**Pull request closed without merging**
